title: luotaishuai的博客
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://.github.com/luotaishuai/luotaishuai.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
#gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: luotaishuai
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: txwwze@126.com

google_analytics: "UA-58263416-1"
